services:
  server:
    hostname: server
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: 'postgres:latest'
    env_file:
      - path: .env
        required: false
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '5432:5432'
